<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <ApplicationIcon>Assets\usb-ejector.ico</ApplicationIcon>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\usb-ejector.ico" />
  </ItemGroup>
</Project>
